name: fyp
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
    

  sqflite:
  path_provider: ^2.0.3
  
  
  
  cupertino_icons: ^1.0.2
  fl_chart: ^0.61.0
  flutter_radar_chart: ^0.2.1
  syncfusion_flutter_charts: ^21.1.38
  flutter_pdfview: ^1.3.1
  webview_flutter: ^4.2.1
  http: ^0.13.6
  chat_gpt_sdk: ^2.1.1
  url_launcher: ^6.1.11
  velocity_x: ^3.6.0
  dio: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0




flutter:
 
 
  uses-material-design: true
  

  
