import './0.3Course.dart';

final List<Course> school1Courses = [
  //SYARAT KELAYAKAN KHAS PROGRAM ALIRAN SAINS-Fakulti Alam Bina
  Course(
    university: 'University Malaya[UM]',
    courseCode: 'UM6581001',
    courseName: 'Sarjana Muda Sains Seni Bina',
    stream: 'Science',
    entryPoints: '3.0-4.0',
    categories1: 'realistic',
    categories2: 'artistic',
  ),
  Course(
    university: 'University Malaya[UM]',
    courseCode: 'UM6581002',
    courseName: 'Sarjana Muda Perancangan Bandar dan Wilayah',
    stream: 'Science',
    entryPoints: '3.00-4.00',
    categories1: 'artistic',
    categories2: 'realistic',
  ),
  Course(
    university: 'University Malaya[UM]',
    courseCode: 'UM6582001',
    courseName: 'Sarjana Muda Ukur Bangunan',
    stream: 'Science',
    entryPoints: '3.00-3.83',
    categories1: 'realistic',
    categories2: 'conventional',
  ),
  Course(
    university: 'University Malaya[UM]',
    courseCode: 'UM6526001',
    courseName: 'Sarjana Muda Ukur Bahan',
    stream: 'Science',
    entryPoints: '3.00-4.00',
    categories1: 'realistic',
    categories2: 'conventional',
  ),
  Course(
    university: 'University Malaya[UM]',
    courseCode: 'UM6341001',
    courseName: 'Sarjana Muda Harta Tanah',
    stream: 'Science',
    entryPoints: '3.00-4.00',
    categories1: 'enterprising',
    categories2: 'social',
  ),
  //Fakulti Kejuruteraan
  Course(
    university: 'University Malaya[UM]',
    courseCode: 'UM6526002',
    courseName: 'Sarjana Muda Kejuruteraan Awam',
    stream: 'Science',
    entryPoints: '3.00-4.00',
    categories1: 'realistic',
    categories2: 'investigative',
  ),
  Course(
    university: 'University Malaya[UM]',
    courseCode: 'UM6524001',
    courseName: 'Sarjana Muda Kejuruteraan Kimia',
    stream: 'Science',
    entryPoints: '3.00-4.00',
    categories1: 'investigative',
    categories2: 'realistic',
  ),
  Course(
    university: 'University Malaya[UM]',
    courseCode: 'UM6521001',
    courseName: 'Sarjana Muda Kejuruteraan Mekanik',
    stream: 'Science',
    entryPoints: '3.00-4.00',
    categories1: 'investigative',
    categories2: 'realistic',
  ),
  Course(
    university: 'University Malaya[UM]',
    courseCode: 'UM6522001',
    courseName: 'Sarjana Muda Kejuruteraan Elektrik',
    stream: 'Science',
    entryPoints: '3.00-4.00',
    categories1: 'realistic',
    categories2: 'investigative',
  ),
  Course(
    university: 'University Malaya[UM]',
    courseCode: 'UM6523001',
    courseName: 'Sarjana Muda Kejuruteraan Bioperubatan',
    stream: 'Science',
    entryPoints: '3.00-4.00',
    categories1: 'investigative',
    categories2: 'realistic',
  ),
  //FAKULTI PERGIGIAN
  Course(
    university: 'University Malaya[UM]',
    courseCode: 'UM6724001',
    courseName: 'SARJANA MUDA PEMBEDAHAN PERGIGIAN',
    stream: 'Science',
    entryPoints: '3.80-4.00',
    categories1: 'investigative',
    categories2: 'realistic',
  ),
  //FAKULTI PERUBATAN
  Course(
    university: 'University Malaya[UM]',
    courseCode: 'UM6721001',
    courseName: 'SARJANA MUDA PERUBATAN DAN SARJANA MUDA PEMBEDAHAN',
    stream: 'Science',
    entryPoints: '3.80-4.00',
    categories1: 'investigative',
    categories2: 'realistic',
  ),
  Course(
    university: 'University Malaya[UM]',
    courseCode: 'UM6725001',
    courseName: 'SARJANA MUDA SAINS BIOPERUBATAN',
    stream: 'Science',
    entryPoints: '3.50-4.00',
    categories1: 'investigative',
    categories2: 'realistic',
  ),
  Course(
    university: 'University Malaya[UM]',
    courseCode: 'UM6723001',
    courseName: 'SARJANA MUDA SAINS KEJURURAWATAN',
    stream: 'Science',
    entryPoints: '3.00-4.00',
    categories1: 'social',
    categories2: 'realistic',
  ),
  //FAKULTI FARMASI
  Course(
    university: 'University Malaya[UM]',
    courseCode: 'UM6727001',
    courseName: 'SARJANA MUDA FARMASI (KEPUJIAN)',
    stream: 'Science',
    entryPoints: '3.80-4.00',
    categories1: 'investigative',
    categories2: 'realistic',
  ),
  //FAKULTI SAINS
  Course(
    university: 'University Malaya[UM]',
    courseCode: 'UM6461001',
    courseName: 'SARJANA MUDA SAINS MATEMATIK',
    stream: 'Science',
    entryPoints: '3.00-4.00',
    categories1: 'investigative',
    categories2: 'conventional',
  ),
  Course(
    university: 'University Malaya[UM]',
    courseCode: 'UM6462001',
    courseName: 'SARJANA MUDA SAINS STATISTIK',
    stream: 'Science',
    entryPoints: '3.00-4.00',
    categories1: 'conventional',
    categories2: 'investigative',
  ),
  Course(
    university: 'University Malaya[UM]',
    courseCode: 'UM6462002',
    courseName: 'SARJANA MUDA SAINS AKTUARI',
    stream: 'Science',
    entryPoints: '3.50-4.00',
    categories1: 'investigative',
    categories2: 'conventional',
  ),
  Course(
    university: 'University Malaya[UM]',
    courseCode: 'UM6441001',
    courseName: 'SARJANA MUDA SAINS FIZIK',
    stream: 'Science',
    entryPoints: '3.00-4.00',
    categories1: 'investigative',
    categories2: 'realistic',
  ),
  Course(
    university: 'University Malaya[UM]',
    courseCode: 'UM6442001',
    courseName: 'SARJANA MUDA SAINS Kimia',
    stream: 'Science',
    entryPoints: '3.00-4.00',
    categories1: 'investigative',
    categories2: 'realistic',
  ),
  Course(
    university: 'University Malaya[UM]',
    courseCode: 'UM6443002',
    courseName: 'SARJANA MUDA SAINS Geologi Gunaan',
    stream: 'Science',
    entryPoints: '3.00-4.00',
    categories1: 'investigative',
    categories2: 'realistic',
  ),
  Course(
    university: 'University Malaya[UM]',
    courseCode: 'UM6421003',
    courseName: 'SARJANA MUDA SAINS Biokimia',
    stream: 'Science',
    entryPoints: '3.00-4.00',
    categories1: 'investigative',
    categories2: 'artistic',
  ),
  Course(
    university: 'University Malaya[UM]',
    courseCode: 'UM6422002',
    courseName: 'SARJANA MUDA SAINS Ekologi dan Biodiversit',
    stream: 'Science',
    entryPoints: '3.00-4.00',
    categories1: 'investigative',
    categories2: 'realistic',
  ),
  Course(
    university: 'University Malaya[UM]',
    courseCode: 'UM6422001',
    courseName: 'SARJANA MUDA Pengurusan Alam Sekitar',
    stream: 'Science',
    entryPoints: '3.00-4.00',
    categories1: 'conventional',
    categories2: 'realistic',
  ),
  Course(
    university: 'University Malaya[UM]',
    courseCode: 'UM6545001',
    courseName: 'SARJANA MUDA Sains Bioteknologi',
    stream: 'Science',
    entryPoints: '3.00-4.00',
    categories1: 'investigative',
    categories2: 'realistic',
  ),
  Course(
    university: 'University Malaya[UM]',
    courseCode: 'UM6421005',
    courseName: 'SARJANA MUDA Sains Genetik dan Mikrobiologi',
    stream: 'Science',
    entryPoints: '3.00-4.00',
    categories1: 'investigative',
    categories2: 'realistic',
  ),
  Course(
    university: 'University Malaya[UM]',
    courseCode: 'UM6142001',
    courseName: 'SARJANA MUDA Sains Dengan Pendidikan',
    stream: 'Science',
    entryPoints: '3.00-4.00',
    categories1: 'investigative',
    categories2: 'social',
  ),
  //FAKULTI SAINS KOMPUTER & TEKNOLOGI MAKLUMAT
  Course(
    university: 'University Malaya[UM]',
    courseCode: 'UM6481001',
    courseName: 'SARJANA MUDA Teknologi Maklumat(Pengkomputeran Multimedia)',
    stream: 'Science',
    entryPoints: '3.00-4.00',
    categories1: 'artistic',
    categories2: 'investigative',
  ),
  Course(
    university: 'University Malaya[UM]',
    courseCode: 'UM6481002',
    courseName: 'SARJANA MUDA Sains Komputer(Kejuruteraan Perisian)',
    stream: 'Science',
    entryPoints: '3.00-4.00',
    categories1: 'reaslistic',
    categories2: 'social',
  ),
  Course(
    university: 'University Malaya[UM]',
    courseCode: 'UM6481003',
    courseName: 'SARJANA MUDA Sains Komputer(Sistem Maklumat)',
    stream: 'Science',
    entryPoints: '3.00-4.00',
    categories1: 'investigative',
    categories2: 'conventional',
  ),
  Course(
    university: 'University Malaya[UM]',
    courseCode: 'UM6481004',
    courseName: 'SARJANA MUDA Sains Komputer(Sistem dan Rangkaian Komputer)',
    stream: 'Science',
    entryPoints: '3.00-4.00',
    categories1: 'artistic',
    categories2: 'reaslistic',
  ),
  Course(
    university: 'University Malaya[UM]',
    courseCode: 'UM6481005',
    courseName: 'SARJANA MUDA Sains Komputer(Kepintaran Buatan)',
    stream: 'Science',
    entryPoints: '3.00-4.00',
    categories1: 'artistic',
    categories2: 'investigative',
  ),
  Course(
    university: 'University Malaya[UM]',
    courseCode: 'UM6481006',
    courseName: 'SARJANA MUDA Sains Komputer(Sains Data)',
    stream: 'Science',
    entryPoints: '3.00-4.00',
    categories1: 'investigative',
    categories2: 'conventional',
  ),
  //PUSAT SUKAN DAN SAINS EKSESAIS
  Course(
    university: 'University Malaya[UM]',
    courseCode: 'UM6813001',
    courseName: 'SARJANA MUDA Sains Sukan',
    stream: 'Science',
    entryPoints: '2.00-4.00',
    categories1: 'reaslistic',
    categories2: 'investigative',
  ),
  Course(
    university: 'University Malaya[UM]',
    courseCode: 'UM6813002',
    courseName: 'SARJANA MUDA Pengurusan Sukan',
    stream: 'Science',
    entryPoints: '2.00-4.00',
    categories1: 'reaslistic',
    categories2: 'social',
  ),

  //AKADEMI PENGAJIAN MELAYU
  Course(
    university: 'University Malaya[UM]',
    courseCode: 'UM6312006',
    courseName: 'SARJANA MUDA Pengajian Melayu',
    stream: 'Art',
    entryPoints: '3.00-4.00',
    categories1: 'investigative',
    categories2: 'reaslistic',
  ),
  Course(
    university: 'University Malaya[UM]',
    courseCode: 'UM6223002',
    courseName: 'SARJANA MUDA Bahasa Melayu Profesional',
    stream: 'Art',
    entryPoints: '3.00-4.00',
    categories1: 'investigative',
    categories2: 'reaslistic',
  ),
  Course(
    university: 'University Malaya[UM]',
    courseCode: 'UM6223003',
    courseName: 'SARJANA MUDA Linguistik Melayu',
    stream: 'Art',
    entryPoints: '3.00-4.00',
    categories1: 'investigative',
    categories2: 'reaslistic',
  ),
  Course(
    university: 'University Malaya[UM]',
    courseCode: 'UM6227001',
    courseName: 'SARJANA MUDA Kesusasteraan Melayu',
    stream: 'Art',
    entryPoints: '3.00-4.00',
    categories1: 'investigative',
    categories2: 'reaslistic',
  ),
  //FAKULTI BAHASA DAN LINGUISTIK
  Course(
    university: 'University Malaya[UM]',
    courseCode: 'UM6224005',
    courseName: 'SARJANA MUDA Bahasa dan Linguistik Perancis',
    stream: 'Art',
    entryPoints: '3.00-4.00',
    categories1: 'social',
    categories2: 'enterprising',
  ),
  Course(
    university: 'University Malaya[UM]',
    courseCode: 'UM6224006',
    courseName: 'SARJANA MUDA Bahasa dan Linguistik Jerman',
    stream: 'Art',
    entryPoints: '3.00-4.00',
    categories1: 'social',
    categories2: 'enterprising',
  ),
  Course(
    university: 'University Malaya[UM]',
    courseCode: 'UM6224008',
    courseName: 'SARJANA MUDA Bahasa dan Linguistik Jepun',
    stream: 'Art',
    entryPoints: '3.00-4.00',
    categories1: 'social',
    categories2: 'enterprising',
  ),
  Course(
    university: 'University Malaya[UM]',
    courseCode: 'UM6224009',
    courseName: 'SARJANA MUDA Bahasa dan Linguistik Sepanyol',
    stream: 'Art',
    entryPoints: '3.00-4.00',
    categories1: 'social',
    categories2: 'enterprising',
  ),
  Course(
    university: 'University Malaya[UM]',
    courseCode: 'UM6224010',
    courseName: 'SARJANA MUDA Bahasa dan Linguistik Itali',
    stream: 'Art',
    entryPoints: '3.00-4.00',
    categories1: 'social',
    categories2: 'enterprising',
  ),
  Course(
    university: 'University Malaya[UM]',
    courseCode: 'UM6224002',
    courseName: 'SARJANA MUDA Bahasa dan Linguistik Inggeris',
    stream: 'Art',
    entryPoints: '3.00-4.00',
    categories1: 'social',
    categories2: 'enterprising',
  ),
  Course(
    university: 'University Malaya[UM]',
    courseCode: 'UM6224004',
    courseName: 'SARJANA MUDA Bahasa dan Linguistik Arab',
    stream: 'Art',
    entryPoints: '3.00-4.00',
    categories1: 'social',
    categories2: 'enterprising',
  ),
  Course(
    university: 'University Malaya[UM]',
    courseCode: 'UM6224003',
    courseName: 'SARJANA MUDA Bahasa dan Linguistik Cina',
    stream: 'Art',
    entryPoints: '3.00-4.00',
    categories1: 'social',
    categories2: 'enterprising',
  ),
  Course(
    university: 'University Malaya[UM]',
    courseCode: 'UM6224007',
    courseName: 'SARJANA MUDA Bahasa dan Linguistik Tamil',
    stream: 'Art',
    entryPoints: '3.00-4.00',
    categories1: 'social',
    categories2: 'enterprising',
  ),
  //FAKULTI PERNIAGAAN DAN EKONOMI
  Course(
    university: 'University Malaya[UM]',
    courseCode: 'UM6344001',
    courseName: 'SARJANA MUDA Perakaunan',
    stream: 'Art',
    entryPoints: '3.30-4.00',
    categories1: 'conventional',
    categories2: 'enterprising',
  ),
  Course(
    university: 'University Malaya[UM]',
    courseCode: 'UM6343001',
    courseName: 'SARJANA MUDA Kewangan',
    stream: 'Art',
    entryPoints: '3.30-4.00',
    categories1: 'enterprising',
    categories2: 'conventional',
  ),
  Course(
    university: 'University Malaya[UM]',
    courseCode: 'UM6345001',
    courseName: 'SARJANA MUDA Pentadbiran Perniagaan',
    stream: 'Art',
    entryPoints: '3.30-4.00',
    categories1: 'enterprising',
    categories2: 'social',
  ),
  Course(
    university: 'University Malaya[UM]',
    courseCode: 'UM6314001',
    courseName: 'SARJANA MUDA Pentadbiran Ekonomi',
    stream: 'Art',
    entryPoints: '3.30-4.00',
    categories1: 'investigative',
    categories2: 'enterprising',
  ),
  //FAKULTI PENDIDIKAN
  Course(
    university: 'University Malaya[UM]',
    courseCode: 'UM6762002',
    courseName: 'SARJANA MUDA Kaunseling',
    stream: 'Art',
    entryPoints: '3.00-4.00',
    categories1: 'social',
    categories2: 'enterprising',
  ),
  Course(
    university: 'University Malaya[UM]',
    courseCode: 'UM6145001',
    courseName:
        'SARJANA MUDA Pendidikan Pengajaran Bahasa Inggeris Sebagai Bahasa Kedua',
    stream: 'Art',
    entryPoints: '3.00-4.00',
    categories1: 'social',
    categories2: 'enterprising',
  ),
  Course(
    university: 'University Malaya[UM]',
    courseCode: 'UM6143001',
    courseName: 'SARJANA MUDA Pendidikan Awal Kanak-Kanak',
    stream: 'Art',
    entryPoints: '3.00-4.00',
    categories1: 'social',
    categories2: 'artistic',
  ),
  //FAKULTI SASTERA DAN SAINS SOSIAL
  Course(
    university: 'University Malaya[UM]',
    courseCode: 'UM6321001',
    courseName: 'SARJANA MUDA Pengajian Media',
    stream: 'Art',
    entryPoints: '3.00-4.00',
    categories1: 'artistic',
    categories2: 'enterprising',
  ),
  Course(
    university: 'University Malaya[UM]',
    courseCode: 'UM6313001',
    courseName: 'SARJANA MUDA Sastera Pengajian Antarabangsa dan Strategik',
    stream: 'Art',
    entryPoints: '3.00-4.00',
    categories1: 'investigative',
    categories2: 'artistic',
  ),
  Course(
      university: 'University Malaya[UM]',
      courseCode: 'UM6312002',
      courseName: 'SARJANA MUDA Sastera Pengajian Asia Tenggara',
      stream: 'Art',
      entryPoints: '3.00-4.00',
      categories1: 'social',
      categories2: 'conventional'),
  Course(
      university: 'University Malaya[UM]',
      courseCode: 'UM6312003',
      courseName: 'SARJANA MUDA Sastera Antropologi dan Sosiologi',
      stream: 'Art',
      entryPoints: '3.00-4.00',
      categories1: 'social',
      categories2: 'enterprising'),
  Course(
      university: 'University Malaya[UM]',
      courseCode: 'UM6312004',
      courseName: 'SARJANA MUDA Pengajian Alam Sekitar',
      stream: 'Art',
      entryPoints: '3.00-4.00',
      categories1: 'reaslistic',
      categories2: 'investigative'),
  Course(
      university: 'University Malaya[UM]',
      courseCode: 'UM6312005',
      courseName: 'SARJANA MUDA Geografi ',
      stream: 'Art',
      entryPoints: '3.00-4.00',
      categories1: 'investigative',
      categories2: 'reaslistic'),
  Course(
      university: 'University Malaya[UM]',
      courseCode: 'UM6762001',
      courseName: 'SARJANA MUDA Pentadbiran Sosial',
      stream: 'Art',
      entryPoints: '3.00-4.00',
      categories1: 'enterprising',
      categories2: 'social'),
  Course(
      university: 'University Malaya[UM]',
      courseCode: 'UM6313002',
      courseName: 'SARJANA MUDA Pengajian Asia Timur',
      stream: 'Art',
      entryPoints: '3.00-4.00',
      categories1: 'social',
      categories2: 'conventional'),
  Course(
      university: 'University Malaya[UM]',
      courseCode: 'UM6225001',
      courseName: 'SARJANA MUDA Sastera Sejarah',
      stream: 'Art',
      entryPoints: '3.00-4.00',
      categories1: 'investigative',
      categories2: 'artistic'),
  Course(
      university: 'University Malaya[UM]',
      courseCode: 'UM6224001',
      courseName: 'SARJANA MUDA Sastera Inggeris',
      stream: 'Art',
      entryPoints: '3.00-4.00',
      categories1: 'investigative',
      categories2: 'artistic'),
  Course(
      university: 'University Malaya[UM]',
      courseCode: 'UM6227002',
      courseName: 'SARJANA MUDA Sastera Pengajian India',
      stream: 'Art',
      entryPoints: '3.00-4.00',
      categories1: 'investigative',
      categories2: 'artistic'),
  Course(
      university: 'University Malaya[UM]',
      courseCode: 'UM6227003',
      courseName: 'SARJANA MUDA Sastera Pengajian Cina',
      stream: 'Art',
      entryPoints: '3.00-4.00',
      categories1: 'investigative',
      categories2: 'artistic'),
  //FAKULTI UNDANG-UNDANG
  Course(
      university: 'University Malaya[UM]',
      courseCode: 'UM6380001',
      courseName: 'SARJANA MUDA Undang-Undang',
      stream: 'Art',
      entryPoints: '3.30-4.00',
      categories1: 'enterprising',
      categories2: 'conventional'),
  //FAKULTI SENI KREATIF
  Course(
      university: 'University Malaya[UM]',
      courseCode: 'UM6380001',
      courseName: 'SARJANA MUDA Muzik',
      stream: 'Art',
      entryPoints: '2.00-4.00',
      categories1: 'artistic',
      categories2: 'investigative'),
  Course(
      university: 'University Malaya[UM]',
      courseCode: 'UM6212002',
      courseName: 'SARJANA MUDA Drama',
      stream: 'Art',
      entryPoints: '2.00-4.00',
      categories1: 'artistic',
      categories2: 'social'),
  Course(
      university: 'University Malaya[UM]',
      courseCode: 'UM6212003',
      courseName: 'SARJANA MUDA Tari',
      stream: 'Art',
      entryPoints: '2.00-4.00',
      categories1: 'artistic',
      categories2: 'social'),
];
